import streamlit as st
import textwrap

st.set_page_config(
    page_title="Reddit Chat Delete Script Generator",
    page_icon="🧹",
    layout="centered"
)

st.title("Reddit Chat Delete Script Generator")
st.caption("Generates a delete-only script for your own sent Reddit chat messages.")

st.warning(
    "This does not ask for your Reddit password. "
    "Run the generated script only on reddit.com/chat in your own browser."
)

username = st.text_input(
    "Reddit username",
    placeholder="without u/"
)

speed = st.slider(
    "Max deletes per minute",
    min_value=20,
    max_value=150,
    value=80,
    step=10
)

generate = st.button("Generate script", type="primary", use_container_width=True)

if generate:
    if not username.strip():
        st.error("Enter your Reddit username first.")
    else:
        script = f"""
// Reddit Chat Own-Message Bulk Delete - Generated by Streamlit
// Deletes only your own sent messages in the CURRENT open chat.
// Does NOT delete Reddit comments.
// Does NOT delete Reddit posts.
// Run on https://www.reddit.com/chat

(async () => {{
  const USERNAME = {username.strip()!r};

  const MAX_DELETES_PER_MINUTE = {int(speed)};
  const DELETE_DELAY_MS = Math.ceil(60000 / MAX_DELETES_PER_MINUTE);

  const SHORT_DELAY_MS = 100;
  const MENU_DELAY_MS = 150;
  const CONFIRM_DELAY_MS = 150;
  const SCROLL_DELAY_MS = 600;

  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

  const escapeRegExp = (value) =>
    value.replace(/[.*+?^${{}}()|[\\]\\\\]/g, "\\\\$&");

  const deepNodes = function* (root = document) {{
    yield root;

    if (root instanceof Element && root.shadowRoot) {{
      yield* deepNodes(root.shadowRoot);
    }}

    const walker = document.createTreeWalker(root, NodeFilter.SHOW_ELEMENT);

    while (walker.nextNode()) {{
      const el = walker.currentNode;
      yield el;

      if (el.shadowRoot) {{
        yield* deepNodes(el.shadowRoot);
      }}
    }}
  }};

  const deepQueryAll = (selector, root = document) => {{
    const out = [];

    for (const node of deepNodes(root)) {{
      if (!node.querySelectorAll) continue;

      try {{
        out.push(...node.querySelectorAll(selector));
      }} catch {{}}
    }}

    return [...new Set(out)];
  }};

  const isVisible = (el) => {{
    if (!el) return false;

    const r = el.getBoundingClientRect();
    const s = getComputedStyle(el);

    return (
      r.width > 0 &&
      r.height > 0 &&
      s.display !== "none" &&
      s.visibility !== "hidden"
    );
  }};

  const localQuery = (root, selector) => {{
    const walk = (node) => {{
      if (!node) return null;

      if (node.querySelector) {{
        try {{
          const found = node.querySelector(selector);
          if (found) return found;
        }} catch {{}}
      }}

      if (node.shadowRoot) {{
        const found = walk(node.shadowRoot);
        if (found) return found;
      }}

      for (const child of node.children || []) {{
        const found = walk(child);
        if (found) return found;
      }}

      return null;
    }};

    return walk(root);
  }};

  const isOwnMessage = (eventEl) => {{
    const msg = localQuery(eventEl, ".room-message[aria-label], [aria-label]");
    const aria = msg?.getAttribute("aria-label") || "";

    return new RegExp(
      "^" + escapeRegExp(USERNAME) + "\\\\s+said\\\\b",
      "i"
    ).test(aria.trim());
  }};

  const findDeleteMenuItem = () => {{
    const items = deepQueryAll(
      '[role="menuitem"], rs-menu-item, rs-dropdown-item, button'
    );

    return items.find((el) => {{
      const text = (
        el.innerText ||
        el.textContent ||
        el.getAttribute("aria-label") ||
        ""
      ).toLowerCase();

      return isVisible(el) && /delete|remove message/.test(text);
    }});
  }};

  const confirmDeleteDialog = async () => {{
    await sleep(CONFIRM_DELAY_MS);

    const buttons = deepQueryAll('button, [role="button"], rs-button')
      .filter(isVisible);

    const confirm = buttons.find((b) => {{
      const text = (b.innerText || b.textContent || "")
        .trim()
        .toLowerCase();

      return (
        text.includes("yes, delete") ||
        text === "delete" ||
        text.includes("confirm")
      );
    }});

    if (confirm) {{
      confirm.click();
      return true;
    }}

    return false;
  }};

  const deleteOne = async (eventEl) => {{
    eventEl.scrollIntoView({{ block: "center" }});

    eventEl.dispatchEvent(
      new MouseEvent("mouseenter", {{
        bubbles: true,
        cancelable: true,
        view: window
      }})
    );

    await sleep(SHORT_DELAY_MS);

    const directDelete = localQuery(
      eventEl,
      [
        '[aria-label="Delete"]',
        '[title="Delete"]',
        '[data-testid="delete-message"]',
        'rs-icon-button[icon="trash"]',
        'rs-icon-button[icon="delete"]',
        'button[aria-label="Delete"]'
      ].join(",")
    );

    if (directDelete && isVisible(directDelete)) {{
      directDelete.click();
    }} else {{
      const more = localQuery(
        eventEl,
        [
          '[aria-label="More options"]',
          '[aria-label="More"]',
          '[title="More"]',
          'button[aria-haspopup="menu"]',
          '[role="button"][aria-haspopup="menu"]',
          'rs-icon-button[icon="more"]'
        ].join(",")
      );

      if (!more || !isVisible(more)) {{
        return false;
      }}

      more.click();
      await sleep(MENU_DELAY_MS);

      const deleteItem = findDeleteMenuItem();

      if (!deleteItem) {{
        return false;
      }}

      deleteItem.click();
    }}

    await confirmDeleteDialog();
    await sleep(DELETE_DELAY_MS);

    return true;
  }};

  const getEvents = () =>
    deepQueryAll("rs-timeline-event")
      .filter(isVisible)
      .filter(isOwnMessage);

  let deleted = 0;
  let failed = 0;
  let lastCount = -1;
  let stuckRounds = 0;

  console.log("Starting Reddit chat cleanup for current chat only...");
  console.log(`Speed: up to ${{MAX_DELETES_PER_MINUTE}} deletes per minute.`);

  while (true) {{
    const ownMessages = getEvents();

    if (ownMessages.length === 0) {{
      stuckRounds++;
    }} else {{
      stuckRounds = 0;
    }}

    for (const msg of ownMessages) {{
      const ok = await deleteOne(msg);

      if (ok) {{
        deleted++;
        console.log(`Deleted ${{deleted}} message(s)...`);
      }} else {{
        failed++;
        console.log(`Skipped/failed ${{failed}} message(s)...`);
      }}
    }}

    const scrollables = deepQueryAll("*").filter((el) => {{
      try {{
        const s = getComputedStyle(el);

        return (
          isVisible(el) &&
          el.scrollHeight > el.clientHeight + 50 &&
          ["auto", "scroll"].includes(s.overflowY)
        );
      }} catch {{
        return false;
      }}
    }});

    const scroller = scrollables.sort(
      (a, b) => b.scrollHeight - a.scrollHeight
    )[0];

    if (scroller) {{
      scroller.scrollTop = 0;
    }} else {{
      window.scrollTo(0, 0);
    }}

    await sleep(SCROLL_DELAY_MS);

    const currentCount = getEvents().length;

    if (currentCount === lastCount) {{
      stuckRounds++;
    }}

    lastCount = currentCount;

    if (stuckRounds >= 3) {{
      break;
    }}
  }}

  console.log(
    `Done. Deleted about ${{deleted}} of your own sent chat message(s) in this open chat.`
  );

  if (failed > 0) {{
    console.log(
      `Skipped or failed about ${{failed}} message(s). Try lowering the speed if too many fail.`
    );
  }}
}})();
"""

        script = textwrap.dedent(script).strip()

        st.success("Script generated.")

        st.markdown(
            """
            **How to run it:**

            1. Open `https://www.reddit.com/chat`.
            2. Open the exact chat thread you want to clean.
            3. Open DevTools.
            4. Go to the **Console** tab.
            5. Paste this script and press Enter.
            """
        )

        st.code(script, language="javascript")

        st.download_button(
            label="Download script as .js",
            data=script,
            file_name="reddit_chat_delete_only.js",
            mime="text/javascript",
            use_container_width=True
        )

st.divider()

st.info(
    "A hosted Streamlit app cannot directly control Reddit in your browser. "
    "This generator avoids collecting your Reddit login and lets the script run only inside your own Reddit tab."
)
